Exporting more from root
DarthBenro008/melonpan pull request #13
Opened 2022-10-03 16:36 UTC by maxpert

Using typescript I had to go around looking for exports like `MelonContext` etc.  the root package should export these. At some level I also feel like the `Melon` prefix from these classes should be removed because they are adding stutter to names. But for now I am sticking to the original convention.

2022-10-03 16:42 UTC, DarthBenro008 requested changes
Thanks for your PR @maxpert ! But i really think only MelonHandler needs to be exported/exposed in this case

2022-10-03 16:42 UTC, DarthBenro008 commented on lib/melopan.ts
> +  RouteHandler as MelonRouteHandler
The `MelonContext`, `MelonMiddleware`, `RouteHandler` are Internal types which i do not think needs to be exported/exposed

2022-10-03 16:45 UTC, maxpert commented on lib/melopan.ts
> +  RouteHandler as MelonRouteHandler
I am not sure how `MelonContext` is internal when your basic example requires:

```
melonpan.get("/", (_, ctx: MelonContext) => ctx.text("Hello world!"));
```

If you are using ts (which I am), you need these definitions. Same goes for Middleware. Right now in order to make everything work I am using:

```
import MelonContext from "melonpan/lib/context";
```

IMO internal is anything that is not visible via external interfaces. In this case it's very obvious it's visible externally.

2022-10-04 06:36 UTC, DarthBenro008 commented on lib/melopan.ts
> +  RouteHandler as MelonRouteHandler
I do agree with the case of `MelonContext`, but `RouteHandler` and `Methods` do not need to be exposed. Maybe in future we can decouple these interfaces

2022-10-04 14:10 UTC, maxpert commented on lib/melopan.ts
> +  RouteHandler as MelonRouteHandler
Removed both for now. I think external interfaces need a careful review.

2022-10-04 14:12 UTC, DarthBenro008 commented
Thanks for the PR @maxpert !

2022-10-04 14:12 UTC, merged